import fs from 'node:fs';
import path from 'node:path';

export interface EnvItem {
  key: string;
  value: string;
  isSecret: boolean;
  comment?: string;
}

export interface EnvData {
  filePath: string;
  fileName: string;
  exists: boolean;
  items: EnvItem[];
  raw: string;
}

export class EnvManager {
  // Check common env file locations in order of precedence
  findEnvPath(dir: string): { filePath: string; fileName: string; exists: boolean } {
    const candidates = ['.env.local', '.env', '.env.development', '.env.example'];
    for (const name of candidates) {
      const full = path.join(dir, name);
      if (fs.existsSync(full)) {
        return { filePath: full, fileName: name, exists: true };
      }
    }
    // Default to .env if none found
    return { filePath: path.join(dir, '.env'), fileName: '.env', exists: false };
  }

  isSecretKey(key: string): boolean {
    return /(KEY|SECRET|TOKEN|PASSWORD|PASS|AUTH|PRIVATE|CREDENTIAL|CERT|DATABASE|API_KEY)/i.test(key);
  }

  getEnv(dir: string): EnvData {
    const { filePath, fileName, exists } = this.findEnvPath(dir);
    if (!exists) {
      return { filePath, fileName, exists: false, items: [], raw: '' };
    }

    try {
      const raw = fs.readFileSync(filePath, 'utf-8');
      const lines = raw.split(/\r?\n/);
      const items: EnvItem[] = [];
      let pendingComment = '';

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;

        if (trimmed.startsWith('#')) {
          pendingComment = (pendingComment ? pendingComment + '\n' : '') + trimmed.replace(/^#\s*/, '');
          continue;
        }

        const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
        if (match) {
          const key = match[1];
          let value = match[2] || '';
          // Remove wrapping quotes if present
          if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
          }

          items.push({
            key,
            value,
            isSecret: this.isSecretKey(key),
            comment: pendingComment || undefined,
          });
          pendingComment = '';
        }
      }

      return {
        filePath,
        fileName,
        exists: true,
        items,
        raw,
      };
    } catch (err) {
      return { filePath, fileName, exists: false, items: [], raw: '' };
    }
  }

  saveEnv(dir: string, items: Array<{ key: string; value: string }>): { success: boolean; filePath: string } {
    const { filePath } = this.findEnvPath(dir);

    // Create a backup if file exists
    if (fs.existsSync(filePath)) {
      try {
        fs.copyFileSync(filePath, `${filePath}.backup`);
      } catch {}
    }

    let content = '# Generated by WinDev Hub .env Studio\n';
    content += `# Updated: ${new Date().toLocaleString()}\n\n`;

    for (const item of items) {
      const key = item.key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, '_');
      if (!key) continue;
      const val = item.value;
      // Quote if contains spaces or special characters
      const needsQuotes = /\s|#|"|'/.test(val);
      const formattedVal = needsQuotes ? `"${val.replace(/"/g, '\\"')}"` : val;
      content += `${key}=${formattedVal}\n`;
    }

    fs.writeFileSync(filePath, content, 'utf-8');
    return { success: true, filePath };
  }
}

export const envManager = new EnvManager();
